language: python
python:
    - '3.7'
git:
    depth: false
services:
    - postgresql
env:
    - DATABASE_URL=postgres://postgres@localhost:5432/perdana_db
before_install:
    - pip install --upgrade pip && python -m pip install pipenv
install:
    - pipenv install --system
before_script:
    - psql -c 'create database perdana_db' -U postgres
script: python manage.py test --settings=config.prod_settings