language: python
python:
    - '3.7'
services:
    - postgresql
env:
    - DATABASE_URL=postgres://perdana@localhost:5432/perdana_db
before_install:
    - pip install --upgrade pip && python -m pip install pipenv
install:
    - pipenv install --system
before_script:
    - psql -c 'create database perdana_db' -U perdana
script: python manage.py test