version: '2.1'

services:
  web:
    image: perdana_indonesia_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    depends_on: 
      - db
    volumes:
      - .:/web
    env_file:
      - ./.env
    environment:
      PYTHONUNBUFFERED: 1

  db:
    container_name: perdana_indonesia_db
    image: "postgres:9.6"
    volumes: 
      - "postgre_data:/var/lib/postgresql/data"
    ports: 
      - "5433:5432"
    env_file: 
      - ./.env

volumes:
  postgre_data: