version: "3.7"

services:
  web:
    container_name: perdana-lobar-web
    image: perdana-lobar-web
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /docker-entrypoint.sh
    networks:
      - perdana_network
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/assets/perdana-lobar/mediafiles:/app/media
      - /var/assets/perdana-lobar/staticfiles:/app/static/root
    environment:
      PYTHONUNBUFFERED: 1

  db:
    container_name: perdana-lobar-db
    image: "mysql:5.7"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - perdana_network
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: masuk123
      MYSQL_DATABASE: perdana_lobar_db

  phpmyadmin:
    container_name: perdana-lobar-phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9.4
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=https://presensi.lombokbaratkab.go.id/phpmyadmin/
    restart: always
    networks:
      - perdana_network
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - "8888:80"
    volumes:
      - /sessions

volumes:
  mysql_data:

networks:
  perdana_network:
    name: perdana_network
