version: '2.1'

services:
  web:
    image: perdana_indonesia_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8088
    expose: :
      - 8088
    depends_on: 
      - db
    volumes:
      - .:/web
    env_file:
      - ./.env
    environment:
      PYTHONUNBUFFERED: 1

  db:
    container_name: perdana_indonesia_db
    image: "postgres:9.6"
    volumes: 
      - "db_data:/var/lib/postgresql/data"
    ports: 
      - "5433:5432"
    env_file: 
      - ./.env.prod.db

volumes:
  db_data: