name: Perdana Indonesia Workflows
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "5.7"
          mysql database: "github-actions"
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          mysql user: "developer"
          mysql password: ${{ secrets.MYSQL_DATABASE_PASSWORD }}
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test
